jobs: 
  - name: Names_Backend_runCI      # required
    type: runCI             # required
    steps:                  # required
      - IN: Names_Backend_ciRepo   # at least one IN or OUT required
      - OUT: Backend_Integration_Tested

  - name: Names_FrontEnd_runCI      # required
    type: runCI             # required
    steps:                  # required
      - IN: Names_FrontEnd_ciRepo   # at least one IN or OUT required
      - OUT: Web_FrontEnd_Integration_Tested

  - name: BACK_INT_Tests
    type: runCLI
    steps:
      - IN: Names_Backend_runCI
      - TASK:                                   
        - script: "echo Starting ...."  

  - name: BACK_To_PROD
    type: runCLI
    steps:
      - IN: BACK_INT_Tests
      - TASK:                                   
        - script: "echo Starting ...."  

  - name: BACK_Prod_Tests
    type: runCLI
    steps:
      - IN: BACK_To_PROD
      - TASK:                                   
        - script: "echo Starting ...." 

  - name: WEB_INT_Tests
    type: runCLI
    steps:
      - IN: Names_FrontEnd_runCI
      - IN: BACK_INT_Tests
      - TASK:                                   
        - script: "echo Starting ...." 
  
  - name: WEB_To_PROD
    type: runCLI
    steps:
      - IN:WEB_INT_Tests
      - TASK:                                   
        - script: "echo Starting ...."  

  - name: WEB_Prod_Tests
    type: runCLI
    steps:
      - IN: WEB_To_PROD
      - IN: BACK_Prod_Tests
      - TASK:                                   
        - script: "echo Starting ...."          