jobs: 
  - name: Names_Backend_runCI      # required
    type: runCI             # required
    steps:                  # required
      - IN: Names_Backend_ciRepo   # at least one IN or OUT required
      - OUT: Backend_Integration_Tested

  - name: Names_FrontEnd_runCI      # required
    type: runCI             # required
    steps:                  # required
      - IN: Names_FrontEnd_ciRepo   # at least one IN or OUT required
      - OUT: Web_FrontEnd_Integration_Tested

  - name: Deploy_Back_To_PROD
    type: runCLI
    steps:
      - IN: Backend_Integration_Tested
      - OUT: Backend_Deployed_in_Production
      - TASK:                                   
        - script: "echo Starting ...."  

  - name: BACK_Prod_Tests
    type: runCLI
    steps:
      - IN: Backend_Deployed_in_Production
      - OUT: Backend_Tested_in_Production
      - TASK:                                   
        - script: "echo Starting ...."  

  - name: Deploy_WEB_to_PROD
    type: runCLI
    steps:
      - IN: Backend_Tested_in_Production
      - IN: Web_FrontEnd_Integration_Tested
      - OUT: Web_FrontEnd_Deployed_in_Production
      - TASK:                                   
        - script: "echo Starting ...." 

  - name: WEB_Prod_Tests
    type: runCLI
    steps:
      - IN: Web_FrontEnd_Deployed_in_Production
      - OUT: Web_FrontEnd_Tested_in_Production
      - TASK:                                   
        - script: "echo Starting ...."          
        
  - name: Build_Mobile_App
    type: runCLI
    steps:
      - IN: Web_FrontEnd_Integration_Tested
      - OUT: Mobile_FrontEnd_Integration_Tested
      - TASK:                                   
        - script: "echo Starting ...."


  - name: Mobile_to_Beta_Testers
    type: runCLI
    steps:
      - IN: Backend_Tested_in_Production
      - IN: Mobile_FrontEnd_Integration_Tested
      - OUT: Mobile_FrontEnd_Deployed_To_Beta_Testers  
      - TASK:                                   
        - script: "echo Starting ...."          
