jobs: 
  - name: Names_Backend_runCI      # required
    type: runCI             # required
    steps:                  # required
      - IN: Names_Backend_ciRepo   # at least one IN or OUT required

  - name: Names_FrontEnd_runCI      # required
    type: runCI             # required
    steps:                  # required
      - IN: Names_FrontEnd_ciRepo   # at least one IN or OUT required

  - name: Deploy_Back_To_PROD
    type: runCLI
    steps:
      - IN: Names_Backend_runCI
      - TASK:
        - script: echo 'Publishing to Production Server at Heroku'
        - script: cd /root/src/github.com/Manakel166/Names_Backend/
        - script: git push -f git@heroku.com:b2u-rest.git master