jobs: 
  - name: Names_Backend_runCI      # required
    type: runCI             # required
    steps:                  # required
      - IN: Names_Backend_ciRepo   # at least one IN or OUT required
      - OUT: Backend_Integration_Tested

  - name: Names_FrontEnd_runCI      # required
    type: runCI             # required
    steps:                  # required
      - IN: Names_FrontEnd_ciRepo   # at least one IN or OUT required
      - OUT: Web_FrontEnd_Integration_Tested

  - name: Deploy_Back_To_PROD
    type: runCLI
    steps:
      - IN: Backend_Integration_Tested
      - OUT: Backend_Deployed_in_Production
      - TASK:                                   
        - script: "echo Starting ...."  

      
  - name: Production_Tests
    type: runCLI
    steps:
      - IN: Backend_Deployed_in_Production
      - OUT: Backend_Tested_in_Production
      - TASK:                                   
        - script: "echo Starting ...."  